import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL = 'https://vwwkzenvcxedxiuopsgv.supabase.co';
const SUPABASE_KEY = 'sb_publishable_Vh9zdSxCUH0fMJOjf_G6Sw_UMU0t0to';
const EMAIL_DOMAIN = 'centraltemp.invalid';
const PRIMARY_USER_ID = 'cba42ab2-7d12-47be-a7e0-c8aba4618796';
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { persistSession: true, autoRefreshToken: true, detectSessionInUrl: false } });

const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const esc = (v='') => String(v ?? '').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const fmtDate = v => v ? new Intl.DateTimeFormat('pt-BR').format(new Date(String(v).length===10 ? `${v}T12:00:00` : v)) : '—';
const fmtDateTime = v => v ? new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v)) : '—';
const fmtTemp = v => v===null||v===undefined||v==='' ? '—' : `${Number(v).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:2})} °C`;
const todayLocal = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`; };
const timeLocal = () => { const d=new Date(); return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}`; };
const monthStart = () => { const d=new Date(); return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`; };
const debounce = (fn,ms=400)=>{let t;return (...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms)}};

const state = {
  session:null,user:null,profile:null,stores:[],sectors:[],equipment:[],readings:[],alerts:[],incidents:[],profiles:[],audit:[],
  route:'dashboard',scope:'network',charts:[],realtime:null,loading:false,
  filters:{},report:{from:monthStart(),to:todayLocal(),tab:'general'},showArchived:false
};

const ROLE_LABEL = {admin:'Administrador',leader:'Líder',agent:'Agente de Prevenção',custom:'Personalizado'};
const STATUS_LABEL = {operational:'Operacional',broken:'Com defeito',maintenance:'Em manutenção',unavailable:'Indisponível'};
const PERMISSIONS = [
  ['dashboard.network','Dashboard da rede'],['dashboard.store','Dashboard da loja'],['stores.view','Visualizar lojas'],['stores.manage','Gerenciar lojas'],
  ['equipment.view','Visualizar equipamentos'],['equipment.manage','Gerenciar setores/equipamentos'],['readings.view','Visualizar coletas'],['readings.create','Registrar coletas'],
  ['alerts.view','Visualizar alertas'],['alerts.manage','Tratar alertas'],['reports.view','Relatórios'],['users.view','Visualizar usuários'],
  ['users.manage_agents','Gerenciar agentes'],['users.manage_all','Gerenciar todos os usuários'],['audit.view','Auditoria']
];
const ROLE_PERMS = {
  admin:['*'],
  leader:['dashboard.store','equipment.view','equipment.manage','readings.view','readings.create','reports.view','users.view','users.manage_agents','alerts.view','alerts.manage'],
  agent:['readings.view','readings.create'],
  custom:[]
};

function can(perm){
  const p=state.profile; if(!p||!p.active) return false;
  if(p.role==='admin') return true;
  if(p.role==='custom') return Array.isArray(p.permissions) && p.permissions.includes(perm);
  return (ROLE_PERMS[p.role]||[]).includes(perm);
}
function isAdmin(){return state.profile?.role==='admin'}
function isLeader(){return state.profile?.role==='leader'}
function isPrimary(){return state.profile?.id===PRIMARY_USER_ID}
function canNetwork(){return isAdmin() || (state.profile?.role==='custom'&&state.profile?.access_scope==='global'&&can('dashboard.network'))}
function accessibleStores(){
  if(!state.profile) return [];
  if(state.profile.role==='admin'||(state.profile.role==='custom'&&state.profile.access_scope==='global')) return state.stores;
  return state.stores.filter(s=>s.id===state.profile.store_id);
}
function currentScopeStore(){return state.scope==='network'?null:state.stores.find(s=>s.id===state.scope)||null}
function scopeFilter(arr){return state.scope==='network'?arr:arr.filter(x=>x.store_id===state.scope)}
function equipmentById(id){return state.equipment.find(x=>x.id===id)}
function storeById(id){return state.stores.find(x=>x.id===id)}
function sectorById(id){return state.sectors.find(x=>x.id===id)}
function profileById(id){return state.profiles.find(x=>x.id===id)}
function outOfRange(r){const e=equipmentById(r.equipment_id); if(!e)return false; const mn=Number(r.temperature_min ?? r.temperature); const mx=Number(r.temperature_max ?? r.temperature); return mn<Number(e.min_temp)||mx>Number(e.max_temp)}
function activeStoreName(id){return storeById(id)?.name||'—'}
function roleLabel(role){return ROLE_LABEL[role]||role||'—'}
function statusClass(v){return v==='operational'||v==='closed'||v==='resolved'||v===true?'ok':v==='broken'||v==='open'||v===false?'bad':v==='maintenance'||v==='acknowledged'?'warn':'muted'}

function setLoading(v,msg='Carregando...'){state.loading=v; const box=$('#globalLoading'); box.classList.toggle('hidden',!v); if(v){$('strong',box).textContent=msg}}
function toast(message,type='success',detail=''){
  const host=$('#toastHost'); const el=document.createElement('div'); el.className=`toast ${type}`;
  el.innerHTML=`<i data-lucide="${type==='error'?'circle-x':type==='warning'?'triangle-alert':'circle-check'}"></i><div><strong>${esc(message)}</strong>${detail?`<p>${esc(detail)}</p>`:''}</div>`;
  host.appendChild(el); icons(); setTimeout(()=>el.remove(),4500);
}
function icons(){window.lucide?.createIcons({attrs:{'stroke-width':1.8}})}
function destroyCharts(){state.charts.forEach(c=>{try{c.destroy()}catch{}});state.charts=[]}
function chart(canvas,config){if(!canvas||!window.Chart)return; const c=new Chart(canvas,config);state.charts.push(c);return c}

async function safeQuery(label, fn){
  try{const {data,error}=await fn(); if(error){console.warn(label,error);return []}return data||[]}catch(e){console.warn(label,e);return []}
}
async function loadData({quiet=false}={}){
  if(!state.session) return;
  if(!quiet)setLoading(true,'Sincronizando dados...');
  try{
    const {data:profile,error:pErr}=await supabase.from('profiles').select('*').eq('id',state.user.id).single();
    if(pErr||!profile) throw pErr||new Error('Perfil não encontrado');
    if(!profile.active){await supabase.auth.signOut();throw new Error('Este usuário está desativado.');}
    state.profile=profile;
    const [stores,sectors,equipment,readings,alerts,incidents,profiles,audit] = await Promise.all([
      safeQuery('stores',()=>supabase.from('stores').select('*').order('code')),
      safeQuery('sectors',()=>supabase.from('sectors').select('*').order('name')),
      safeQuery('equipment',()=>supabase.from('equipment').select('*').order('name')),
      safeQuery('readings',()=>supabase.from('readings').select('*').order('created_at',{ascending:false}).limit(5000)),
      safeQuery('alerts',()=>supabase.from('temperature_alerts').select('*').order('created_at',{ascending:false}).limit(2500)),
      safeQuery('incidents',()=>supabase.from('equipment_incidents').select('*').order('created_at',{ascending:false}).limit(2500)),
      can('users.view')||isAdmin()?safeQuery('profiles',()=>supabase.from('profiles').select('*').order('full_name')):Promise.resolve([profile]),
      can('audit.view')?safeQuery('audit',()=>supabase.from('audit_logs').select('*').order('created_at',{ascending:false}).limit(2500)):Promise.resolve([])
    ]);
    Object.assign(state,{stores,sectors,equipment,readings,alerts,incidents,profiles,audit});
    if(!state.profiles.some(p=>p.id===profile.id)) state.profiles.unshift(profile);
    if(!canNetwork()) state.scope=profile.store_id || (stores[0]?.id??'network');
    if(state.scope!=='network'&&!stores.some(s=>s.id===state.scope)) state.scope=canNetwork()?'network':profile.store_id;
    renderShell(); renderRoute(); subscribeRealtime();
  } finally {if(!quiet)setLoading(false)}
}

function subscribeRealtime(){
  if(state.realtime) return;
  const reload=debounce(()=>loadData({quiet:true}),700);
  state.realtime=supabase.channel('central-temp-live')
    .on('postgres_changes',{event:'*',schema:'public',table:'readings'},reload)
    .on('postgres_changes',{event:'*',schema:'public',table:'temperature_alerts'},reload)
    .on('postgres_changes',{event:'*',schema:'public',table:'equipment'},reload)
    .on('postgres_changes',{event:'*',schema:'public',table:'equipment_incidents'},reload)
    .on('postgres_changes',{event:'*',schema:'public',table:'stores'},reload)
    .on('postgres_changes',{event:'*',schema:'public',table:'sectors'},reload)
    .subscribe();
}

const NAV = [
  ['dashboard','layout-dashboard','Dashboard',()=>can('dashboard.store')||can('dashboard.network')||isAdmin()],
  ['stores','store','Lojas',()=>isAdmin()||isLeader()||can('stores.view')||can('stores.manage')],
  ['equipment','refrigerator','Equipamentos',()=>can('equipment.view')||can('equipment.manage')||can('readings.create')],
  ['collections','thermometer','Coletas',()=>can('readings.view')||can('readings.create')],
  ['alerts','bell','Alertas',()=>can('alerts.view')],
  ['reports','chart-no-axes-combined','Relatórios',()=>can('reports.view')],
  ['users','users','Usuários',()=>can('users.view')],
  ['account','circle-user-round','Minha Conta',()=>true],
  ['audit','shield-check','Auditoria',()=>can('audit.view')]
];
function navVisible(){return NAV.filter(x=>x[3]())}
function navigate(route){state.route=route;closeSidebar();renderShell();renderRoute();window.scrollTo({top:0,behavior:'smooth'})}
function renderShell(){
  const nav=$('#navMenu');
  nav.innerHTML=navVisible().map(([r,ic,l])=>`<button class="nav-item ${state.route===r?'active':''}" data-route="${r}"><i data-lucide="${ic}"></i><span>${l}</span>${r==='alerts'&&state.alerts.filter(a=>a.status==='open').length?`<span class="nav-badge">${state.alerts.filter(a=>a.status==='open').length}</span>`:''}</button>`).join('');
  $$('.nav-item',nav).forEach(b=>b.onclick=()=>navigate(b.dataset.route));
  const p=state.profile;
  $('#sidebarUser').innerHTML=`<div class="avatar"><img src="./assets/nilo-mascote.webp" alt=""></div><div><strong>${esc(p.full_name)}</strong><small>${esc(roleLabel(p.role))}${isPrimary()?' • Principal':''}</small></div>`;
  const scopeHost=$('#scopeSelectorHost');
  if(canNetwork()){
    scopeHost.innerHTML=`<select id="scopeSelect" class="select scope-select"><option value="network">Rede Geral</option>${accessibleStores().filter(s=>s.active||state.scope===s.id).map(s=>`<option value="${s.id}" ${state.scope===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select>`;
    $('#scopeSelect').value=state.scope; $('#scopeSelect').onchange=e=>{state.scope=e.target.value;renderRoute()};
  }else scopeHost.innerHTML='';
  const bnav=$('#mobileBottomNav'); const mobile=[['dashboard','house','Início'],['stores','store','Lojas'],['collections','thermometer','Coletas'],['alerts','bell','Alertas'],['account','menu','Mais']].filter(x=>navVisible().some(n=>n[0]===x[0])||x[0]==='account');
  bnav.innerHTML=mobile.map(([r,i,l])=>`<button class="mobile-nav-item ${state.route===r?'active':''}" data-route="${r}"><i data-lucide="${i}"></i><span>${l}</span></button>`).join('');
  $$('.mobile-nav-item',bnav).forEach(b=>b.onclick=()=>navigate(b.dataset.route));
  $('#quickCollectionBtn').classList.toggle('hidden',!can('readings.create')); icons();
}

function setPage(title,subtitle=''){ $('#pageTitle').textContent=title; $('#pageSubtitle').textContent=subtitle; }
function renderRoute(){
  destroyCharts();
  const allowed=navVisible().map(x=>x[0]); if(!allowed.includes(state.route)) state.route=allowed[0]||'account';
  ({dashboard:renderDashboard,stores:renderStores,equipment:renderEquipment,collections:renderCollections,alerts:renderAlerts,reports:renderReports,users:renderUsers,account:renderAccount,audit:renderAudit}[state.route]||renderDashboard)();
  renderShell(); icons();
}

function readingStatus(r){return outOfRange(r)?'<span class="status bad">Fora do padrão</span>':'<span class="status ok">Normal</span>'}
function equipmentStatus(e){return `<span class="status ${statusClass(e.operational_status)}">${esc(STATUS_LABEL[e.operational_status]||e.operational_status)}</span>`}
function activeBadge(active){return active?'<span class="status ok">Ativo</span>':'<span class="status muted">Arquivado</span>'}
function pageHeader(title,sub,actions=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div><div class="page-actions">${actions}</div></div>`}
function empty(text,icon='inbox'){return `<div class="empty"><i data-lucide="${icon}"></i><div>${esc(text)}</div></div>`}

function renderDashboard(){
  const store=currentScopeStore(); setPage(store?store.name:'Prevenção de Perdas',store?'Visão operacional da loja':'Visão geral da rede');
  const reads=scopeFilter(state.readings); const equips=scopeFilter(state.equipment).filter(e=>e.active); const stores=state.scope==='network'?state.stores.filter(s=>s.active):(store?[store]:[]); const alerts=scopeFilter(state.alerts); const incidents=scopeFilter(state.incidents);
  const today=todayLocal(); const todayReads=reads.filter(r=>r.reading_date===today); const openAlerts=alerts.filter(a=>a.status!=='closed'); const badEquip=new Set(reads.filter(outOfRange).map(r=>r.equipment_id)); const incidentOpen=incidents.filter(i=>i.status==='open');
  const content=$('#content');
  content.innerHTML=`${pageHeader(store?`Dashboard — ${esc(store.name)}`:'Dashboard Geral da Rede',store?'Acompanhe coletas, alertas e equipamentos desta unidade.':'Acompanhe os principais indicadores de temperatura de todas as lojas.',can('reports.view')?'<button class="btn ghost" id="dashReport"><i data-lucide="file-chart-column"></i>Relatório</button>':'')}
  <div class="grid kpi-grid">
    ${kpi('thermometer',todayReads.length,'Coletas do dia','Meta mínima: 3 por equipamento','blue')}
    ${kpi('triangle-alert',badEquip.size,'Equipamentos fora do padrão',openAlerts.length+' alertas em acompanhamento','red')}
    ${kpi('store',stores.length,store?'Loja selecionada':'Lojas monitoradas',`${equips.length} equipamentos ativos`,'green')}
    ${kpi('bell',openAlerts.length+incidentOpen.length,'Alertas / ocorrências ativas',`${incidentOpen.length} incidentes de equipamento`,'orange')}
  </div>
  <div class="grid two-col">
    <section class="card"><div class="card-head"><div><h3>Recorrência de desvios</h3><p>Coletas fora da faixa nos últimos 7 dias</p></div><span class="status info">7 dias</span></div><div class="chart-box"><canvas id="recurrenceChart"></canvas></div></section>
    <section class="card"><div class="card-head"><div><h3>Situação dos equipamentos</h3><p>Status operacional atual</p></div></div><div class="chart-box small"><canvas id="equipmentChart"></canvas></div></section>
  </div>
  <div class="grid two-col">
    <section class="card"><div class="card-head"><div><h3>Meta diária — 3 coletas</h3><p>Progresso por equipamento hoje</p></div></div>${dailyGoals(equips,todayReads)}</section>
    <section class="card"><div class="card-head"><div><h3>Equipamentos que exigem atenção</h3><p>Recorrência, defeitos e manutenção</p></div></div>${problemEquipment(equips,reads,incidents)}</section>
  </div>
  <section class="card"><div class="card-head"><div><h3>Últimas coletas</h3><p>Dados mais recentes da operação</p></div><button class="btn ghost sm" id="seeCollections">Ver todas</button></div>${recentReadings(reads.slice(0,8))}</section>`;
  $('#seeCollections').onclick=()=>navigate('collections'); if($('#dashReport'))$('#dashReport').onclick=()=>navigate('reports');
  renderDashboardCharts(reads,equips); icons();
}
function kpi(icon,value,label,sub,kind){return `<article class="kpi"><div class="kpi-icon ${kind}"><i data-lucide="${icon}"></i></div><div><strong>${esc(value)}</strong><small>${esc(label)}</small><em>${esc(sub)}</em></div></article>`}
function dailyGoals(equips,todayReads){
  if(!equips.length)return empty('Cadastre equipamentos para acompanhar a meta diária.','thermometer');
  return equips.slice(0,10).map(e=>{const n=todayReads.filter(r=>r.equipment_id===e.id).length;const pct=Math.min(100,(n/3)*100);return `<div class="goal-row"><div><strong>${esc(e.name)}</strong><small>${esc(activeStoreName(e.store_id))}${e.sector_id?' • '+esc(sectorById(e.sector_id)?.name||''):''}</small></div><b>${n>=3?'3/3 +':`${n}/3`}</b><div class="progress ${n<3?'red':''}"><span style="width:${pct}%"></span></div></div>`}).join('')
}
function problemEquipment(equips,reads,incidents){
  const rows=equips.map(e=>{const deviations=reads.filter(r=>r.equipment_id===e.id&&outOfRange(r)).length;const incident=incidents.find(i=>i.equipment_id===e.id&&i.status==='open');return {e,deviations,incident}}).filter(x=>x.deviations>=2||x.e.operational_status!=='operational'||x.incident).sort((a,b)=>b.deviations-a.deviations).slice(0,8);
  if(!rows.length)return empty('Nenhum equipamento com recorrência ou defeito no período.','circle-check');
  return rows.map(x=>`<div class="metric-row"><div><strong>${esc(x.e.name)}</strong><span> ${esc(activeStoreName(x.e.store_id))}</span></div><div>${x.e.operational_status!=='operational'?equipmentStatus(x.e):`<span class="status warn">${x.deviations} desvios</span>`}</div></div>`).join('')
}
function recentReadings(reads){
  if(!reads.length)return empty('Nenhuma coleta registrada ainda.','thermometer');
  const rows=reads.map(r=>`<tr><td>${fmtDate(r.reading_date)} ${esc(String(r.reading_time||'').slice(0,5))}</td><td>${esc(activeStoreName(r.store_id))}</td><td>${esc(equipmentById(r.equipment_id)?.name||'—')}</td><td>${fmtTemp(r.temperature_avg??r.temperature)}</td><td>${readingStatus(r)}</td><td>${esc(r.responsible_name)}</td></tr>`).join('');
  return `<div class="table-wrap desktop-table"><table class="table"><thead><tr><th>Data/Hora</th><th>Loja</th><th>Equipamento</th><th>Temperatura</th><th>Status</th><th>Responsável</th></tr></thead><tbody>${rows}</tbody></table></div><div class="mobile-cards">${reads.map(r=>`<div class="entity-card"><div class="entity-card-head"><div><h4>${esc(equipmentById(r.equipment_id)?.name||'Equipamento')}</h4><p>${esc(activeStoreName(r.store_id))} • ${fmtDate(r.reading_date)} ${esc(String(r.reading_time||'').slice(0,5))}</p></div>${readingStatus(r)}</div><div class="entity-meta"><div><small>Temperatura</small><strong>${fmtTemp(r.temperature_avg??r.temperature)}</strong></div><div><small>Responsável</small><strong>${esc(r.responsible_name)}</strong></div></div></div>`).join('')}</div>`
}
function renderDashboardCharts(reads,equips){
  const labels=[],vals=[]; for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;labels.push(`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}`);vals.push(reads.filter(r=>r.reading_date===key&&outOfRange(r)).length)}
  chart($('#recurrenceChart'),{type:'line',data:{labels,datasets:[{label:'Desvios',data:vals,borderColor:'#e83b3f',backgroundColor:'rgba(232,59,63,.10)',fill:true,tension:.35,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0},grid:{color:'#edf1f5'}},x:{grid:{display:false}}}}});
  const counts=['operational','broken','maintenance','unavailable'].map(s=>equips.filter(e=>e.operational_status===s).length);
  chart($('#equipmentChart'),{type:'doughnut',data:{labels:['Operacional','Com defeito','Em manutenção','Indisponível'],datasets:[{data:counts,backgroundColor:['#159447','#e83b3f','#f5a400','#8a97a8'],borderWidth:0}]},options:{responsive:true,maintainAspectRatio:false,cutout:'66%',plugins:{legend:{position:'bottom',labels:{boxWidth:10,font:{size:10}}}}}})
}

function renderStores(){
  setPage('Lojas','Gestão das unidades e seus setores'); const canManage=isAdmin()&&can('stores.manage'); const list=state.stores.filter(s=>state.showArchived?!s.active:s.active);
  $('#content').innerHTML=`${pageHeader('Lojas','Crie, edite, desative ou arquive lojas. Setores são gerenciados dentro de cada unidade.',`${canManage?'<button class="btn primary" id="newStore"><i data-lucide="plus"></i>Nova Loja</button>':''}<button class="btn ghost" id="toggleArchived"><i data-lucide="archive"></i>${state.showArchived?'Ver ativas':'Ver arquivadas'}</button>`)}
  ${state.showArchived?'<div class="archive-banner"><span>Exibindo lojas arquivadas/desativadas.</span></div>':''}
  <div class="filters"><input id="storeSearch" class="input grow" placeholder="Buscar por loja, código ou cidade..."></div>
  <section class="card" id="storeList">${storesTable(list,canManage)}</section>`;
  $('#toggleArchived').onclick=()=>{state.showArchived=!state.showArchived;renderStores()}; if($('#newStore'))$('#newStore').onclick=()=>openStoreModal(); $('#storeSearch').oninput=e=>{const q=e.target.value.toLowerCase();$('#storeList').innerHTML=storesTable(list.filter(s=>[s.name,s.code,s.city].join(' ').toLowerCase().includes(q)),canManage);bindStoreActions()}; bindStoreActions(); icons();
}
function storesTable(list,canManage){
  if(!list.length)return empty(state.showArchived?'Nenhuma loja arquivada.':'Nenhuma loja cadastrada.','store');
  return `<div class="table-wrap desktop-table"><table class="table"><thead><tr><th>Código</th><th>Loja</th><th>Cidade</th><th>Status</th><th>Setores</th><th>Equipamentos</th><th></th></tr></thead><tbody>${list.map(s=>`<tr><td>${esc(s.code)}</td><td><strong>${esc(s.name)}</strong></td><td>${esc(s.city||'—')}</td><td>${activeBadge(s.active)}</td><td>${state.sectors.filter(x=>x.store_id===s.id&&x.active).length}</td><td>${state.equipment.filter(x=>x.store_id===s.id&&x.active).length}</td><td><div class="td-actions"><button class="btn ghost sm store-sectors" data-id="${s.id}"><i data-lucide="layers-3"></i>Setores</button>${canManage?`<button class="btn ghost icon store-edit" data-id="${s.id}" title="Editar"><i data-lucide="pencil"></i></button><button class="btn ${s.active?'danger':'success'} icon store-remove" data-id="${s.id}" title="${s.active?'Excluir/Arquivar':'Restaurar'}"><i data-lucide="${s.active?'trash-2':'rotate-ccw'}"></i></button>`:''}</div></td></tr>`).join('')}</tbody></table></div><div class="mobile-cards">${list.map(s=>`<div class="entity-card"><div class="entity-card-head"><div><h4>${esc(s.name)}</h4><p>Código ${esc(s.code)} • ${esc(s.city||'Sem cidade')}</p></div>${activeBadge(s.active)}</div><div class="entity-meta"><div><small>Setores</small><strong>${state.sectors.filter(x=>x.store_id===s.id&&x.active).length}</strong></div><div><small>Equipamentos</small><strong>${state.equipment.filter(x=>x.store_id===s.id&&x.active).length}</strong></div></div><div class="entity-actions"><button class="btn ghost sm store-sectors" data-id="${s.id}">Setores</button>${canManage?`<button class="btn ghost sm store-edit" data-id="${s.id}">Editar</button><button class="btn ${s.active?'danger':'success'} sm store-remove" data-id="${s.id}">${s.active?'Excluir/Arquivar':'Restaurar'}</button>`:''}</div></div>`).join('')}</div>`
}
function bindStoreActions(){ $$('.store-edit').forEach(b=>b.onclick=()=>openStoreModal(storeById(b.dataset.id))); $$('.store-sectors').forEach(b=>b.onclick=()=>openSectorsModal(storeById(b.dataset.id))); $$('.store-remove').forEach(b=>b.onclick=()=>{const s=storeById(b.dataset.id); s.active?removeEntity('store',s):restoreEntity('store',s)}); icons() }
function openStoreModal(s=null){
  modal(`${s?'Editar':'Nova'} Loja`, `<form id="storeForm" class="form-grid"><div class="field"><label class="required">Código</label><input class="input" name="code" required value="${esc(s?.code||'')}"></div><div class="field"><label class="required">Nome da loja</label><input class="input" name="name" required value="${esc(s?.name||'')}"></div><div class="field full"><label>Cidade</label><input class="input" name="city" value="${esc(s?.city||'')}"></div></form>`, `<button class="btn ghost" data-close>Cancelar</button><button class="btn primary" id="saveStore">Salvar</button>`,'small');
  $('#saveStore').onclick=async()=>{const f=$('#storeForm');if(!f.reportValidity())return;const d=Object.fromEntries(new FormData(f));setLoading(true,'Salvando loja...');try{const q=s?supabase.from('stores').update({code:d.code.trim(),name:d.name.trim(),city:d.city.trim()||null,updated_at:new Date().toISOString()}).eq('id',s.id):supabase.from('stores').insert({code:d.code.trim(),name:d.name.trim(),city:d.city.trim()||null});const {error}=await q;if(error)throw error;closeModal();await loadData({quiet:true});toast('Loja salva com sucesso.')}catch(e){toast('Não foi possível salvar a loja.','error',e.message)}finally{setLoading(false)}}
}
function openSectorsModal(store){
  const canManage=can('equipment.manage')&&(isAdmin()||state.profile.store_id===store.id||state.profile.access_scope==='global'); const sectors=state.sectors.filter(s=>s.store_id===store.id&&s.active);
  modal(`Setores — ${store.name}`, `<div class="page-actions" style="margin-bottom:12px">${canManage?'<button class="btn primary sm" id="newSector"><i data-lucide="plus"></i>Novo setor</button>':''}</div><div id="sectorModalList">${sectorList(store,sectors,canManage)}</div>`, `<button class="btn ghost" data-close>Fechar</button>`,'small');
  if($('#newSector'))$('#newSector').onclick=()=>openSectorEdit(store);bindSectorActions(store);icons()
}
function sectorList(store,list,canManage){if(!list.length)return empty('Nenhum setor cadastrado nesta loja.','layers-3');return list.map(s=>`<div class="metric-row"><div><strong>${esc(s.name)}</strong><span> ${state.equipment.filter(e=>e.sector_id===s.id&&e.active).length} equipamentos</span></div><div class="td-actions">${canManage?`<button class="btn ghost icon sector-edit" data-id="${s.id}"><i data-lucide="pencil"></i></button><button class="btn danger icon sector-remove" data-id="${s.id}"><i data-lucide="trash-2"></i></button>`:''}</div></div>`).join('')}
function bindSectorActions(store){$$('.sector-edit').forEach(b=>b.onclick=()=>openSectorEdit(store,sectorById(b.dataset.id)));$$('.sector-remove').forEach(b=>b.onclick=()=>removeEntity('sector',sectorById(b.dataset.id)));icons()}
function openSectorEdit(store,sector=null){modal(`${sector?'Editar':'Novo'} setor`, `<form id="sectorForm"><div class="field"><label class="required">Nome do setor</label><input class="input" name="name" required value="${esc(sector?.name||'')}"></div></form>`,`<button class="btn ghost" data-close>Cancelar</button><button class="btn primary" id="saveSector">Salvar</button>`,'small');$('#saveSector').onclick=async()=>{const f=$('#sectorForm');if(!f.reportValidity())return;const name=new FormData(f).get('name').trim();setLoading(true,'Salvando setor...');try{const q=sector?supabase.from('sectors').update({name,updated_at:new Date().toISOString()}).eq('id',sector.id):supabase.from('sectors').insert({store_id:store.id,name,created_by:state.user.id});const {error}=await q;if(error)throw error;closeModal();await loadData({quiet:true});toast('Setor salvo.');openSectorsModal(store)}catch(e){toast('Erro ao salvar setor.','error',e.message)}finally{setLoading(false)}}}

function renderEquipment(){
  setPage('Equipamentos','Faixas de temperatura, setores e situação operacional'); const canManage=can('equipment.manage'); const all=scopeFilter(state.equipment).filter(e=>state.showArchived?!e.active:e.active);
  $('#content').innerHTML=`${pageHeader('Equipamentos','Gerencie equipamentos por loja e setor, incluindo coleta 1x ou 3x.',`${canManage?'<button class="btn primary" id="newEquipment"><i data-lucide="plus"></i>Novo Equipamento</button>':''}<button class="btn ghost" id="toggleArchived"><i data-lucide="archive"></i>${state.showArchived?'Ver ativos':'Ver arquivados'}</button>`)}
  <div class="filters"><input id="equipmentSearch" class="input grow" placeholder="Buscar equipamento..."><select id="equipmentStatus" class="select"><option value="">Todos os status</option>${Object.entries(STATUS_LABEL).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></div><section id="equipmentList" class="card">${equipmentTable(all,canManage)}</section>`;
  $('#toggleArchived').onclick=()=>{state.showArchived=!state.showArchived;renderEquipment()}; if($('#newEquipment'))$('#newEquipment').onclick=()=>openEquipmentModal(); const apply=()=>{const q=$('#equipmentSearch').value.toLowerCase(),st=$('#equipmentStatus').value;const f=all.filter(e=>(!q||[e.name,e.category,activeStoreName(e.store_id),sectorById(e.sector_id)?.name].join(' ').toLowerCase().includes(q))&&(!st||e.operational_status===st));$('#equipmentList').innerHTML=equipmentTable(f,canManage);bindEquipmentActions()};$('#equipmentSearch').oninput=apply;$('#equipmentStatus').onchange=apply;bindEquipmentActions();icons()
}
function equipmentTable(list,canManage){
  if(!list.length)return empty('Nenhum equipamento encontrado.','refrigerator');
  return `<div class="table-wrap desktop-table"><table class="table"><thead><tr><th>Equipamento</th><th>Loja</th><th>Setor</th><th>Faixa</th><th>Coleta</th><th>Situação</th><th></th></tr></thead><tbody>${list.map(e=>`<tr><td><strong>${esc(e.name)}</strong><br><small>${esc(e.category)}</small></td><td>${esc(activeStoreName(e.store_id))}</td><td>${esc(sectorById(e.sector_id)?.name||'Sem setor')}</td><td>${fmtTemp(e.min_temp)} a ${fmtTemp(e.max_temp)}</td><td><span class="status info">${e.samples_per_collection}x</span></td><td>${e.active?equipmentStatus(e):activeBadge(false)}</td><td><div class="td-actions">${can('readings.create')&&e.active?`<button class="btn accent icon equipment-collect" data-id="${e.id}" title="Coletar"><i data-lucide="thermometer"></i></button>`:''}${canManage?`<button class="btn ghost icon equipment-edit" data-id="${e.id}"><i data-lucide="pencil"></i></button><button class="btn ${e.active?'danger':'success'} icon equipment-remove" data-id="${e.id}"><i data-lucide="${e.active?'trash-2':'rotate-ccw'}"></i></button>`:''}</div></td></tr>`).join('')}</tbody></table></div><div class="mobile-cards">${list.map(e=>`<div class="entity-card"><div class="entity-card-head"><div><h4>${esc(e.name)}</h4><p>${esc(activeStoreName(e.store_id))} • ${esc(sectorById(e.sector_id)?.name||'Sem setor')}</p></div>${e.active?equipmentStatus(e):activeBadge(false)}</div><div class="entity-meta"><div><small>Faixa</small><strong>${fmtTemp(e.min_temp)} a ${fmtTemp(e.max_temp)}</strong></div><div><small>Modo de coleta</small><strong>${e.samples_per_collection}x</strong></div></div><div class="entity-actions">${can('readings.create')&&e.active?`<button class="btn accent sm equipment-collect" data-id="${e.id}">Registrar coleta</button>`:''}${canManage?`<button class="btn ghost sm equipment-edit" data-id="${e.id}">Editar</button><button class="btn ${e.active?'danger':'success'} sm equipment-remove" data-id="${e.id}">${e.active?'Excluir/Arquivar':'Restaurar'}</button>`:''}</div></div>`).join('')}</div>`
}
function bindEquipmentActions(){ $$('.equipment-edit').forEach(b=>b.onclick=()=>openEquipmentModal(equipmentById(b.dataset.id))); $$('.equipment-collect').forEach(b=>b.onclick=()=>openCollectionModal(equipmentById(b.dataset.id))); $$('.equipment-remove').forEach(b=>b.onclick=()=>{const e=equipmentById(b.dataset.id);e.active?removeEntity('equipment',e):restoreEntity('equipment',e)});icons() }
function openEquipmentModal(e=null){
  const stores=accessibleStores().filter(s=>s.active); const defaultStore=e?.store_id||(state.scope!=='network'?state.scope:stores[0]?.id); const sectors=state.sectors.filter(s=>s.store_id===defaultStore&&s.active);
  modal(`${e?'Editar':'Novo'} Equipamento`, `<form id="equipmentForm" class="form-grid cols3"><div class="field"><label class="required">Loja</label><select class="select" name="store_id" id="eqStore" required>${stores.map(s=>`<option value="${s.id}" ${s.id===defaultStore?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Setor</label><select class="select" name="sector_id" id="eqSector"><option value="">Sem setor</option>${sectors.map(s=>`<option value="${s.id}" ${s.id===e?.sector_id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label class="required">Categoria</label><input class="input" name="category" required value="${esc(e?.category||'')}"></div><div class="field full"><label class="required">Nome do equipamento</label><input class="input" name="name" required value="${esc(e?.name||'')}"></div><div class="field"><label class="required">Temperatura ideal</label><input class="input" name="target_temp" type="number" step="0.1" required value="${e?.target_temp??''}"></div><div class="field"><label class="required">Mínima</label><input class="input" name="min_temp" type="number" step="0.1" required value="${e?.min_temp??''}"></div><div class="field"><label class="required">Máxima</label><input class="input" name="max_temp" type="number" step="0.1" required value="${e?.max_temp??''}"></div><div class="field"><label class="required">Medições por coleta</label><select class="select" name="samples_per_collection"><option value="1" ${e?.samples_per_collection!==3?'selected':''}>1x — uma temperatura</option><option value="3" ${e?.samples_per_collection===3?'selected':''}>3x — três temperaturas</option></select></div><div class="field"><label>Situação</label><select class="select" name="operational_status">${Object.entries(STATUS_LABEL).map(([v,l])=>`<option value="${v}" ${v===(e?.operational_status||'operational')?'selected':''}>${l}</option>`).join('')}</select></div><div class="field full"><label>Observação da situação</label><textarea class="textarea" name="status_note">${esc(e?.status_note||'')}</textarea></div></form>`, `<button class="btn ghost" data-close>Cancelar</button><button class="btn primary" id="saveEquipment">Salvar</button>`,'large');
  $('#eqStore').onchange=ev=>{const ss=state.sectors.filter(s=>s.store_id===ev.target.value&&s.active);$('#eqSector').innerHTML=`<option value="">Sem setor</option>${ss.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}`};
  $('#saveEquipment').onclick=async()=>{const f=$('#equipmentForm');if(!f.reportValidity())return;const d=Object.fromEntries(new FormData(f));const mn=Number(d.min_temp),tg=Number(d.target_temp),mx=Number(d.max_temp);if(!(mn<=tg&&tg<=mx)){toast('Faixa de temperatura inválida.','warning','A mínima deve ser ≤ ideal ≤ máxima.');return}const payload={store_id:d.store_id,sector_id:d.sector_id||null,name:d.name.trim(),category:d.category.trim(),target_temp:tg,min_temp:mn,max_temp:mx,samples_per_collection:Number(d.samples_per_collection),operational_status:d.operational_status,status_note:d.status_note.trim()||null,status_updated_at:new Date().toISOString(),updated_at:new Date().toISOString()};if(!e)payload.created_by=state.user.id;setLoading(true,'Salvando equipamento...');try{const {error}=await (e?supabase.from('equipment').update(payload).eq('id',e.id):supabase.from('equipment').insert(payload));if(error)throw error;closeModal();await loadData({quiet:true});toast('Equipamento salvo.')}catch(err){toast('Erro ao salvar equipamento.','error',err.message)}finally{setLoading(false)}};icons()
}

async function removeEntity(type,item){
  const labels={store:'loja',sector:'setor',equipment:'equipamento'}; const name=item.name; const linked = type==='store' ? (state.sectors.some(x=>x.store_id===item.id)||state.equipment.some(x=>x.store_id===item.id)||state.readings.some(x=>x.store_id===item.id)||state.profiles.some(x=>x.store_id===item.id)) : type==='sector' ? (state.equipment.some(x=>x.sector_id===item.id)||state.incidents.some(x=>x.sector_id===item.id)) : (state.readings.some(x=>x.equipment_id===item.id)||state.alerts.some(x=>x.equipment_id===item.id)||state.incidents.some(x=>x.equipment_id===item.id));
  const title=linked?`Arquivar ${labels[type]}`:`Excluir ${labels[type]}`; const confirmExtra=type==='store'?`<div class="field"><label>Digite <strong>${esc(name)}</strong> para confirmar</label><input class="input" id="confirmName" autocomplete="off"></div>`:'';
  modal(title, `<div class="danger-zone"><strong>${linked?'Histórico protegido':'Exclusão definitiva'}</strong><p>${linked?`Este ${labels[type]} possui vínculos ou histórico. Ele será arquivado e continuará disponível nos relatórios históricos.`:`Este ${labels[type]} ainda não possui histórico vinculado e poderá ser excluído definitivamente.`}</p></div><div class="field" style="margin-top:12px"><label>Motivo</label><textarea id="removeReason" class="textarea" placeholder="Informe o motivo..."></textarea></div>${confirmExtra}`, `<button class="btn ghost" data-close>Cancelar</button><button class="btn danger" id="confirmRemove">${linked?'Arquivar':'Excluir definitivamente'}</button>`,'small');
  $('#confirmRemove').onclick=async()=>{if(type==='store'&&$('#confirmName').value.trim()!==name){toast('Digite exatamente o nome da loja para confirmar.','warning');return}const reason=$('#removeReason').value.trim();setLoading(true,linked?'Arquivando...':'Excluindo...');try{const table=type==='store'?'stores':type==='sector'?'sectors':'equipment';let error;if(linked){({error}=await supabase.from(table).update({active:false,archived_at:new Date().toISOString(),archived_by:state.user.id,archive_reason:reason||'Arquivado pelo sistema',updated_at:new Date().toISOString()}).eq('id',item.id))}else{({error}=await supabase.from(table).delete().eq('id',item.id))}if(error)throw error;closeModal();await loadData({quiet:true});toast(linked?`${name} arquivado com segurança.`:`${name} excluído.`)}catch(e){toast('A operação não foi concluída.','error',e.message)}finally{setLoading(false)}}
}
async function restoreEntity(type,item){const table=type==='store'?'stores':type==='sector'?'sectors':'equipment';setLoading(true,'Restaurando...');try{const {error}=await supabase.from(table).update({active:true,archived_at:null,archived_by:null,archive_reason:null,updated_at:new Date().toISOString()}).eq('id',item.id);if(error)throw error;await loadData({quiet:true});toast(`${item.name} restaurado.`)}catch(e){toast('Não foi possível restaurar.','error',e.message)}finally{setLoading(false)}}

function renderCollections(){
  setPage('Coletas','Histórico e registro de temperaturas'); let list=scopeFilter(state.readings); const q=state.filters.collectionSearch||'', status=state.filters.collectionStatus||'', from=state.filters.collectionFrom||'',to=state.filters.collectionTo||''; list=list.filter(r=>(!q||[activeStoreName(r.store_id),equipmentById(r.equipment_id)?.name,r.responsible_name].join(' ').toLowerCase().includes(q.toLowerCase()))&&(!status||(status==='normal'?!outOfRange(r):outOfRange(r)))&&(!from||r.reading_date>=from)&&(!to||r.reading_date<=to));
  $('#content').innerHTML=`${pageHeader('Coletas de Temperatura','Cada equipamento deve ter pelo menos 3 coletas por dia. Equipamentos 3x registram três medições no mesmo momento.',can('readings.create')?'<button class="btn accent" id="newCollection"><i data-lucide="plus"></i>Nova Coleta</button>':'')}
  <div class="filters"><input id="collectionSearch" class="input grow" value="${esc(q)}" placeholder="Buscar por loja, equipamento ou responsável..."><select id="collectionStatus" class="select"><option value="">Todos os status</option><option value="normal" ${status==='normal'?'selected':''}>Normal</option><option value="deviation" ${status==='deviation'?'selected':''}>Fora do padrão</option></select><input id="collectionFrom" type="date" class="input" value="${from}"><input id="collectionTo" type="date" class="input" value="${to}"></div><section class="card" id="collectionList">${collectionsTable(list)}</section>`;
  if($('#newCollection'))$('#newCollection').onclick=()=>openCollectionModal(); const apply=()=>{state.filters.collectionSearch=$('#collectionSearch').value;state.filters.collectionStatus=$('#collectionStatus').value;state.filters.collectionFrom=$('#collectionFrom').value;state.filters.collectionTo=$('#collectionTo').value;renderCollections()};$('#collectionSearch').oninput=debounce(apply,250);$('#collectionStatus').onchange=apply;$('#collectionFrom').onchange=apply;$('#collectionTo').onchange=apply;bindCollectionActions();icons()
}
function collectionsTable(list){
  if(!list.length)return empty('Nenhuma coleta encontrada para os filtros selecionados.','thermometer');
  return `<div class="table-wrap desktop-table"><table class="table"><thead><tr><th>Data/Hora</th><th>Loja / Setor</th><th>Equipamento</th><th>Medições</th><th>Média</th><th>Status</th><th>Responsável</th><th></th></tr></thead><tbody>${list.slice(0,500).map(r=>`<tr><td>${fmtDate(r.reading_date)} ${esc(String(r.reading_time||'').slice(0,5))}</td><td>${esc(activeStoreName(r.store_id))}<br><small>${esc(sectorById(equipmentById(r.equipment_id)?.sector_id)?.name||'—')}</small></td><td>${esc(equipmentById(r.equipment_id)?.name||'—')}</td><td>${r.sample_count===3?[r.temperature_1,r.temperature_2,r.temperature_3].map(fmtTemp).join(' / '):fmtTemp(r.temperature_1??r.temperature)}</td><td>${fmtTemp(r.temperature_avg??r.temperature)}</td><td>${readingStatus(r)}</td><td>${esc(r.responsible_name)}</td><td><div class="td-actions"><button class="btn ghost icon collection-view" data-id="${r.id}"><i data-lucide="eye"></i></button>${isAdmin()?`<button class="btn danger icon collection-delete" data-id="${r.id}"><i data-lucide="trash-2"></i></button>`:''}</div></td></tr>`).join('')}</tbody></table></div><div class="mobile-cards">${list.slice(0,200).map(r=>`<div class="entity-card"><div class="entity-card-head"><div><h4>${esc(equipmentById(r.equipment_id)?.name||'Equipamento')}</h4><p>${esc(activeStoreName(r.store_id))} • ${fmtDate(r.reading_date)} ${esc(String(r.reading_time||'').slice(0,5))}</p></div>${readingStatus(r)}</div><div class="entity-meta"><div><small>Média</small><strong>${fmtTemp(r.temperature_avg??r.temperature)}</strong></div><div><small>Medições</small><strong>${r.sample_count}x</strong></div></div><div class="entity-actions"><button class="btn ghost sm collection-view" data-id="${r.id}">Detalhes</button>${isAdmin()?`<button class="btn danger sm collection-delete" data-id="${r.id}">Excluir</button>`:''}</div></div>`).join('')}</div>`
}
function bindCollectionActions(){ $$('.collection-view').forEach(b=>b.onclick=()=>viewCollection(state.readings.find(r=>r.id===b.dataset.id))); $$('.collection-delete').forEach(b=>b.onclick=()=>deleteCollection(state.readings.find(r=>r.id===b.dataset.id)));icons() }
function viewCollection(r){const e=equipmentById(r.equipment_id);modal('Detalhes da coleta',`<div class="form-grid"><div class="field"><label>Loja</label><div>${esc(activeStoreName(r.store_id))}</div></div><div class="field"><label>Equipamento</label><div>${esc(e?.name||'—')}</div></div><div class="field"><label>Data/Hora</label><div>${fmtDate(r.reading_date)} ${esc(String(r.reading_time||'').slice(0,8))}</div></div><div class="field"><label>Responsável</label><div>${esc(r.responsible_name)}</div></div><div class="field full"><label>Medições</label><div class="temp-result">${[r.temperature_1,r.temperature_2,r.temperature_3].slice(0,r.sample_count).map((v,i)=>`<div><small>${i+1}ª medição</small><strong>${fmtTemp(v)}</strong></div>`).join('')}</div></div><div class="field"><label>Média</label><div>${fmtTemp(r.temperature_avg)}</div></div><div class="field"><label>Mínima / Máxima</label><div>${fmtTemp(r.temperature_min)} / ${fmtTemp(r.temperature_max)}</div></div><div class="field"><label>Condição do equipamento</label><div>${esc(STATUS_LABEL[r.equipment_condition]||r.equipment_condition)}</div></div><div class="field full"><label>Ação corretiva</label><div>${esc(r.corrective_action||'—')}</div></div><div class="field full"><label>Observações</label><div>${esc(r.notes||r.equipment_issue_note||'—')}</div></div></div>`,`<button class="btn ghost" data-close>Fechar</button>`,'large')}
function deleteCollection(r){modal('Excluir coleta',`<div class="danger-zone"><strong>Esta ação será auditada.</strong><p>A coleta de ${esc(equipmentById(r.equipment_id)?.name||'equipamento')} em ${fmtDate(r.reading_date)} será excluída. Alertas vinculados podem ser removidos pelo banco.</p></div>`,`<button class="btn ghost" data-close>Cancelar</button><button class="btn danger" id="confirmDeleteCollection">Excluir coleta</button>`,'small');$('#confirmDeleteCollection').onclick=async()=>{setLoading(true,'Excluindo coleta...');try{const {error}=await supabase.from('readings').delete().eq('id',r.id);if(error)throw error;closeModal();await loadData({quiet:true});toast('Coleta excluída e registrada na auditoria.')}catch(e){toast('Não foi possível excluir a coleta.','error',e.message)}finally{setLoading(false)}}}
function openCollectionModal(preselected=null){
  const stores=accessibleStores().filter(s=>s.active); const defaultStore=preselected?.store_id||(state.scope!=='network'?state.scope:state.profile.store_id)||stores[0]?.id; const sectors=state.sectors.filter(s=>s.store_id===defaultStore&&s.active); const equips=state.equipment.filter(e=>e.store_id===defaultStore&&e.active&&(preselected?e.id===preselected.id:true));
  modal('Registrar Coleta',`<div class="collection-stepper"><div class="collection-step active">1. Loja</div><div class="collection-step active">2. Setor</div><div class="collection-step active">3. Equipamento</div><div class="collection-step active">4. Temperatura</div></div><form id="collectionForm" class="form-grid"><div class="field"><label class="required">Loja</label><select class="select" id="colStore" name="store_id" required>${stores.map(s=>`<option value="${s.id}" ${s.id===defaultStore?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field"><label>Setor</label><select class="select" id="colSector"><option value="">Todos</option>${sectors.map(s=>`<option value="${s.id}" ${s.id===preselected?.sector_id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field full"><label class="required">Equipamento</label><select class="select" id="colEquipment" name="equipment_id" required><option value="">Selecione</option>${equips.map(e=>`<option value="${e.id}" ${e.id===preselected?.id?'selected':''}>${esc(e.name)}</option>`).join('')}</select></div><div id="collectionTempArea" class="full"></div><div class="field"><label>Condição do equipamento</label><select class="select" id="colCondition" name="equipment_condition">${Object.entries(STATUS_LABEL).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></div><div class="field" id="issueField" style="display:none"><label>Descrição do problema</label><input class="input" name="equipment_issue_note" placeholder="Descreva o defeito ou indisponibilidade"></div><div class="field full" id="correctiveField" style="display:none"><label class="required">Ação corretiva</label><textarea class="textarea" name="corrective_action" id="correctiveAction" placeholder="Informe a ação tomada diante do desvio"></textarea></div><div class="field full"><label>Observações</label><textarea class="textarea" name="notes" placeholder="Observações adicionais..."></textarea></div></form>`,`<button class="btn ghost" data-close>Cancelar</button><button class="btn accent" id="saveCollection"><i data-lucide="check"></i>Registrar coleta</button>`,'large');
  const updateEquipOptions=()=>{const sid=$('#colStore').value,sec=$('#colSector').value;const es=state.equipment.filter(e=>e.active&&e.store_id===sid&&(!sec||e.sector_id===sec));$('#colEquipment').innerHTML=`<option value="">Selecione</option>${es.map(e=>`<option value="${e.id}">${esc(e.name)}</option>`).join('')}`;renderTempArea()};
  const updateSectors=()=>{const sid=$('#colStore').value;const ss=state.sectors.filter(s=>s.active&&s.store_id===sid);$('#colSector').innerHTML=`<option value="">Todos</option>${ss.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}`;updateEquipOptions()};
  const renderTempArea=()=>{const e=equipmentById($('#colEquipment').value);const area=$('#collectionTempArea');if(!e){area.innerHTML='<div class="notice-box">Selecione um equipamento para carregar a faixa e o modo de coleta.</div>';return}const count=e.samples_per_collection||1;area.innerHTML=`<div class="notice-box"><strong>${esc(e.name)}</strong> • Faixa permitida: <strong>${fmtTemp(e.min_temp)} a ${fmtTemp(e.max_temp)}</strong> • Coleta <strong>${count}x</strong></div><div class="temperature-inputs" style="margin-top:12px">${Array.from({length:count},(_,i)=>`<div class="field"><label class="required">${count===1?'Temperatura':`${i+1}ª temperatura`} (°C)</label><input class="input col-temp" type="number" step="0.1" name="temperature_${i+1}" required inputmode="decimal"></div>`).join('')}</div><div id="tempPreview"></div>`;$$('.col-temp').forEach(x=>x.oninput=previewTemp);previewTemp()};
  const previewTemp=()=>{const e=equipmentById($('#colEquipment').value);if(!e)return;const vals=$$('.col-temp').map(x=>x.value===''?null:Number(x.value));if(vals.some(v=>v===null)){if($('#tempPreview'))$('#tempPreview').innerHTML='';$('#correctiveField').style.display='none';return}const avg=vals.reduce((a,b)=>a+b,0)/vals.length,mn=Math.min(...vals),mx=Math.max(...vals),bad=mn<Number(e.min_temp)||mx>Number(e.max_temp);$('#tempPreview').innerHTML=`<div class="temp-result"><div><small>Média</small><strong>${fmtTemp(avg)}</strong></div><div><small>Mínima</small><strong>${fmtTemp(mn)}</strong></div><div><small>Máxima</small><strong>${fmtTemp(mx)}</strong></div></div>${bad?'<div class="alert-box"><strong>Fora do padrão.</strong> Uma ou mais medições estão fora da faixa do equipamento. A ação corretiva é obrigatória.</div>':''}`;$('#correctiveField').style.display=bad?'block':'none';$('#correctiveAction').required=bad};
  $('#colStore').onchange=updateSectors;$('#colSector').onchange=updateEquipOptions;$('#colEquipment').onchange=renderTempArea;$('#colCondition').onchange=e=>{$('#issueField').style.display=e.target.value==='operational'?'none':'block';const inp=$('[name="equipment_issue_note"]');inp.required=e.target.value!=='operational'}; if(preselected){$('#colEquipment').value=preselected.id;renderTempArea()} else renderTempArea();
  $('#saveCollection').onclick=async()=>{const f=$('#collectionForm');if(!f.reportValidity())return;const d=Object.fromEntries(new FormData(f));const e=equipmentById(d.equipment_id);if(!e)return;const vals=$$('.col-temp').map(x=>Number(x.value));const payload={equipment_id:e.id,store_id:e.store_id,temperature:vals.reduce((a,b)=>a+b,0)/vals.length,temperature_1:vals[0],temperature_2:vals[1]??null,temperature_3:vals[2]??null,reading_date:todayLocal(),reading_time:timeLocal(),responsible_name:state.profile.full_name,notes:d.notes?.trim()||null,corrective_action:d.corrective_action?.trim()||null,created_by:state.user.id,equipment_condition:d.equipment_condition||'operational',equipment_issue_note:d.equipment_issue_note?.trim()||null};setLoading(true,'Registrando coleta...');try{const {error}=await supabase.from('readings').insert(payload);if(error)throw error;closeModal();await loadData({quiet:true});toast('Coleta registrada com sucesso.')}catch(err){toast('Não foi possível registrar a coleta.','error',err.message)}finally{setLoading(false)}};icons()
}

function renderAlerts(){
  setPage('Alertas','Desvios de temperatura e ocorrências de equipamentos'); let alerts=scopeFilter(state.alerts); const incidents=scopeFilter(state.incidents); const st=state.filters.alertStatus||''; if(st)alerts=alerts.filter(a=>a.status===st);
  $('#content').innerHTML=`${pageHeader('Alertas e Ocorrências','Acompanhe, reconheça e encerre desvios. Ocorrências de equipamento ficam vinculadas ao histórico.','')}
  <div class="filters"><select id="alertStatus" class="select"><option value="">Todos os status</option><option value="open" ${st==='open'?'selected':''}>Abertos</option><option value="acknowledged" ${st==='acknowledged'?'selected':''}>Reconhecidos</option><option value="closed" ${st==='closed'?'selected':''}>Encerrados</option></select></div>
  <div class="grid two-col"><section class="card"><div class="card-head"><div><h3>Alertas de temperatura</h3><p>${alerts.filter(a=>a.status!=='closed').length} em acompanhamento</p></div></div>${alertsTable(alerts)}</section><section class="card"><div class="card-head"><div><h3>Ocorrências de equipamento</h3><p>Defeitos, manutenção e indisponibilidade</p></div></div>${incidentsList(incidents)}</section></div>`;
  $('#alertStatus').onchange=e=>{state.filters.alertStatus=e.target.value;renderAlerts()};bindAlertActions();bindIncidentActions();icons()
}
function alertsTable(list){if(!list.length)return empty('Nenhum alerta encontrado.','bell');return `<div class="table-wrap"><table class="table"><thead><tr><th>Data</th><th>Equipamento</th><th>Loja</th><th>Status</th><th></th></tr></thead><tbody>${list.slice(0,300).map(a=>`<tr><td>${fmtDateTime(a.created_at)}</td><td><strong>${esc(equipmentById(a.equipment_id)?.name||'—')}</strong><br><small>${esc(a.message)}</small></td><td>${esc(activeStoreName(a.store_id))}</td><td><span class="status ${statusClass(a.status)}">${a.status==='open'?'Aberto':a.status==='acknowledged'?'Reconhecido':'Encerrado'}</span></td><td><div class="td-actions">${can('alerts.manage')&&a.status==='open'?`<button class="btn warning sm alert-ack" data-id="${a.id}">Reconhecer</button>`:''}${can('alerts.manage')&&a.status!=='closed'?`<button class="btn success sm alert-close" data-id="${a.id}">Encerrar</button>`:''}</div></td></tr>`).join('')}</tbody></table></div>`}
function incidentsList(list){const open=list.filter(i=>i.status==='open');if(!list.length)return empty('Nenhuma ocorrência de equipamento.','wrench');return list.slice(0,30).map(i=>`<div class="metric-row"><div><strong>${esc(equipmentById(i.equipment_id)?.name||'—')}</strong><span> ${esc(STATUS_LABEL[i.incident_type]||i.incident_type)} • ${fmtDateTime(i.opened_at)}</span></div><div>${i.status==='open'?(can('equipment.manage')?`<button class="btn success sm incident-resolve" data-id="${i.id}">Resolver</button>`:'<span class="status bad">Aberta</span>'):'<span class="status ok">Resolvida</span>'}</div></div>`).join('')}
function bindAlertActions(){ $$('.alert-ack').forEach(b=>b.onclick=()=>updateAlert(b.dataset.id,'acknowledged')); $$('.alert-close').forEach(b=>b.onclick=()=>updateAlert(b.dataset.id,'closed')) }
async function updateAlert(id,status){setLoading(true,'Atualizando alerta...');try{const payload=status==='acknowledged'?{status,acknowledged_by:state.user.id,acknowledged_at:new Date().toISOString()}:{status,closed_by:state.user.id,closed_at:new Date().toISOString()};const {error}=await supabase.from('temperature_alerts').update(payload).eq('id',id);if(error)throw error;await loadData({quiet:true});toast(status==='closed'?'Alerta encerrado.':'Alerta reconhecido.')}catch(e){toast('Erro ao atualizar alerta.','error',e.message)}finally{setLoading(false)}}
function bindIncidentActions(){$$('.incident-resolve').forEach(b=>b.onclick=()=>resolveIncident(state.incidents.find(i=>i.id===b.dataset.id)))}
function resolveIncident(i){modal('Resolver ocorrência',`<div class="field"><label class="required">Solução / providência</label><textarea id="incidentResolution" class="textarea" required placeholder="Descreva o que foi feito..."></textarea></div>`,`<button class="btn ghost" data-close>Cancelar</button><button class="btn success" id="saveResolution">Marcar como resolvida</button>`,'small');$('#saveResolution').onclick=async()=>{const resolution=$('#incidentResolution').value.trim();if(!resolution){toast('Informe a solução adotada.','warning');return}setLoading(true,'Resolvendo ocorrência...');try{const {error}=await supabase.from('equipment_incidents').update({status:'resolved',resolution,resolved_by:state.user.id,resolved_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',i.id);if(error)throw error;closeModal();await loadData({quiet:true});toast('Ocorrência resolvida e equipamento atualizado.')}catch(e){toast('Erro ao resolver ocorrência.','error',e.message)}finally{setLoading(false)}}}

function reportReadings(){return scopeFilter(state.readings).filter(r=>(!state.report.from||r.reading_date>=state.report.from)&&(!state.report.to||r.reading_date<=state.report.to))}
function renderReports(){
  setPage('Relatórios','Análise gerencial por período, loja, setor e equipamento'); const reads=reportReadings(); const alerts=scopeFilter(state.alerts).filter(a=>{const d=String(a.created_at).slice(0,10);return(!state.report.from||d>=state.report.from)&&(!state.report.to||d<=state.report.to)}); const compliant=reads.filter(r=>!outOfRange(r)).length; const rate=reads.length?Math.round(compliant/reads.length*100):0; const vals=reads.map(r=>Number(r.temperature_avg??r.temperature)).filter(Number.isFinite); const min=vals.length?Math.min(...vals):null,max=vals.length?Math.max(...vals):null; const tab=state.report.tab;
  $('#content').innerHTML=`${pageHeader('Relatórios','Consolide a operação e exporte os dados para análise.',`<button class="btn ghost" id="exportExcel"><i data-lucide="sheet"></i>Excel</button><button class="btn primary" id="printReport"><i data-lucide="printer"></i>Imprimir / PDF</button>`)}
  <div class="filters"><label class="field"><small>De</small><input id="reportFrom" type="date" class="input" value="${state.report.from}"></label><label class="field"><small>Até</small><input id="reportTo" type="date" class="input" value="${state.report.to}"></label></div>
  <div class="grid report-summary">${reportKpi(reads.length,'Coletas no período')}${reportKpi(alerts.length,'Alertas gerados')}${reportKpi(`${rate}%`,'Conformidade')}${reportKpi(fmtTemp(min),'Menor temperatura')}${reportKpi(fmtTemp(max),'Maior temperatura')}</div>
  <section class="card"><div class="report-tabs">${[['general','Resumo Geral'],['stores','Por Loja'],['equipment','Por Equipamento'],['alerts','Alertas'],['performance','Meta 3/dia']].map(([v,l])=>`<button class="report-tab ${tab===v?'active':''}" data-tab="${v}">${l}</button>`).join('')}</div><div id="reportBody">${reportBody(tab,reads,alerts)}</div></section>`;
  $('#reportFrom').onchange=e=>{state.report.from=e.target.value;renderReports()};$('#reportTo').onchange=e=>{state.report.to=e.target.value;renderReports()};$$('.report-tab').forEach(b=>b.onclick=()=>{state.report.tab=b.dataset.tab;renderReports()});$('#exportExcel').onclick=()=>exportReportExcel(reads);$('#printReport').onclick=()=>window.print();if(tab==='general')renderReportChart(reads);icons()
}
function reportKpi(v,l){return `<div class="card report-card"><strong>${esc(v)}</strong><small>${esc(l)}</small></div>`}
function reportBody(tab,reads,alerts){
  if(tab==='general')return `<div class="grid two-col"><div><div class="chart-box"><canvas id="reportChart"></canvas></div></div><div>${recurrenceReport(reads)}</div></div>${recentReadings(reads.slice(0,25))}`;
  if(tab==='stores'){const rows=accessibleStores().map(s=>{const rr=reads.filter(r=>r.store_id===s.id),bad=rr.filter(outOfRange).length;return {s,n:rr.length,bad,rate:rr.length?Math.round((rr.length-bad)/rr.length*100):0}});return simpleTable(['Loja','Coletas','Desvios','Conformidade'],rows.map(x=>[x.s.name,x.n,x.bad,`${x.rate}%`]));}
  if(tab==='equipment'){const rows=scopeFilter(state.equipment).map(e=>{const rr=reads.filter(r=>r.equipment_id===e.id),bad=rr.filter(outOfRange).length;return [e.name,activeStoreName(e.store_id),rr.length,bad,bad>=2?'Recorrente':'—']}).sort((a,b)=>b[3]-a[3]);return simpleTable(['Equipamento','Loja','Coletas','Desvios','Recorrência'],rows)}
  if(tab==='alerts')return alertsTable(alerts);
  if(tab==='performance'){const days=[...new Set(reads.map(r=>r.reading_date))].sort().reverse().slice(0,31);const rows=[];days.forEach(d=>scopeFilter(state.equipment).filter(e=>e.active).forEach(e=>{const n=reads.filter(r=>r.reading_date===d&&r.equipment_id===e.id).length;rows.push([fmtDate(d),e.name,activeStoreName(e.store_id),`${Math.min(n,3)}/3${n>3?' +':''}`,n>=3?'Cumprida':'Pendente'])}));return simpleTable(['Data','Equipamento','Loja','Meta','Status'],rows.slice(0,600));}
  return ''
}
function recurrenceReport(reads){const map={};reads.filter(outOfRange).forEach(r=>map[r.equipment_id]=(map[r.equipment_id]||0)+1);const rows=Object.entries(map).filter(([,n])=>n>=2).sort((a,b)=>b[1]-a[1]).slice(0,10);return `<div class="card-head"><div><h3>Equipamentos recorrentes</h3><p>2 ou mais desvios no período</p></div></div>${rows.length?rows.map(([id,n])=>`<div class="metric-row"><strong>${esc(equipmentById(id)?.name||'—')}</strong><span class="status warn">${n} desvios</span></div>`).join(''):empty('Nenhuma recorrência no período.','circle-check')}`}
function renderReportChart(reads){const days={};reads.forEach(r=>{days[r.reading_date]??={sum:0,n:0};days[r.reading_date].sum+=Number(r.temperature_avg??r.temperature);days[r.reading_date].n++});const keys=Object.keys(days).sort();chart($('#reportChart'),{type:'line',data:{labels:keys.map(fmtDate),datasets:[{label:'Temperatura média',data:keys.map(k=>days[k].sum/days[k].n),borderColor:'#1e67d6',backgroundColor:'rgba(30,103,214,.08)',fill:true,tension:.3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false}},y:{grid:{color:'#edf1f5'}}}}})}
function simpleTable(headers,rows){if(!rows.length)return empty('Sem dados para este relatório.','chart-no-axes-combined');return `<div class="table-wrap"><table class="table"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function exportReportExcel(reads){if(!window.XLSX){toast('Biblioteca de Excel não carregada.','error');return}const rows=reads.map(r=>({Data:r.reading_date,Hora:String(r.reading_time||'').slice(0,8),Loja:activeStoreName(r.store_id),Setor:sectorById(equipmentById(r.equipment_id)?.sector_id)?.name||'',Equipamento:equipmentById(r.equipment_id)?.name||'',Medicao1:r.temperature_1,Medicao2:r.temperature_2,Medicao3:r.temperature_3,Media:r.temperature_avg??r.temperature,Minima:r.temperature_min,Maxima:r.temperature_max,Status:outOfRange(r)?'Fora do padrão':'Normal',Responsavel:r.responsible_name,AcaoCorretiva:r.corrective_action||'',CondicaoEquipamento:STATUS_LABEL[r.equipment_condition]||r.equipment_condition,Observacoes:r.notes||''}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),'Coletas');XLSX.writeFile(wb,`Relatorio_Temperatura_${state.report.from}_${state.report.to}.xlsx`)}

function renderUsers(){
  setPage('Usuários','Perfis, lojas e permissões de acesso'); const list=state.profiles; const canManage=isAdmin()||can('users.manage_all')||can('users.manage_agents');
  $('#content').innerHTML=`${pageHeader('Usuários','Administrador, Líder, Agente de Prevenção e perfis personalizados.',canManage?'<button class="btn primary" id="newUser"><i data-lucide="user-plus"></i>Novo Usuário</button>':'')}
  <div class="filters"><input id="userSearch" class="input grow" placeholder="Buscar usuário..."></div><section id="userList" class="card">${usersTable(list,canManage)}</section>`;
  if($('#newUser'))$('#newUser').onclick=()=>openUserModal();$('#userSearch').oninput=e=>{const q=e.target.value.toLowerCase();$('#userList').innerHTML=usersTable(list.filter(p=>[p.full_name,p.username,roleLabel(p.role),activeStoreName(p.store_id)].join(' ').toLowerCase().includes(q)),canManage);bindUserActions()};bindUserActions();icons()
}
function usersTable(list,canManage){if(!list.length)return empty('Nenhum usuário encontrado.','users');return `<div class="table-wrap desktop-table"><table class="table"><thead><tr><th>Nome</th><th>Usuário</th><th>Perfil</th><th>Loja</th><th>Status</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td><strong>${esc(p.full_name)}</strong>${p.id===PRIMARY_USER_ID?' <span class="primary-account"><i data-lucide="shield"></i>Principal</span>':''}</td><td>${esc(p.username)}</td><td><span class="role-badge">${esc(roleLabel(p.role))}</span></td><td>${p.access_scope==='global'?'Rede Geral':esc(activeStoreName(p.store_id))}</td><td>${activeBadge(p.active)}</td><td><div class="td-actions">${canManage&&p.id!==PRIMARY_USER_ID?`<button class="btn ghost icon user-edit" data-id="${p.id}"><i data-lucide="pencil"></i></button><button class="btn ${p.active?'warning':'success'} icon user-toggle" data-id="${p.id}"><i data-lucide="${p.active?'user-x':'user-check'}"></i></button>${isAdmin()?`<button class="btn danger icon user-delete" data-id="${p.id}"><i data-lucide="trash-2"></i></button>`:''}`:p.id===PRIMARY_USER_ID?'<span class="status info">Protegido</span>':''}</div></td></tr>`).join('')}</tbody></table></div><div class="mobile-cards">${list.map(p=>`<div class="entity-card"><div class="entity-card-head"><div><h4>${esc(p.full_name)}</h4><p>@${esc(p.username)} • ${esc(roleLabel(p.role))}</p></div>${activeBadge(p.active)}</div><div class="entity-meta"><div><small>Acesso</small><strong>${p.access_scope==='global'?'Rede Geral':esc(activeStoreName(p.store_id))}</strong></div><div><small>Conta</small><strong>${p.id===PRIMARY_USER_ID?'Principal':'Padrão'}</strong></div></div>${canManage&&p.id!==PRIMARY_USER_ID?`<div class="entity-actions"><button class="btn ghost sm user-edit" data-id="${p.id}">Editar</button><button class="btn ${p.active?'warning':'success'} sm user-toggle" data-id="${p.id}">${p.active?'Desativar':'Ativar'}</button>${isAdmin()?`<button class="btn danger sm user-delete" data-id="${p.id}">Excluir</button>`:''}</div>`:''}</div>`).join('')}</div>`}
function bindUserActions(){ $$('.user-edit').forEach(b=>b.onclick=()=>openUserModal(profileById(b.dataset.id))); $$('.user-toggle').forEach(b=>b.onclick=()=>toggleUser(profileById(b.dataset.id))); $$('.user-delete').forEach(b=>b.onclick=()=>deleteUser(profileById(b.dataset.id)));icons() }
function openUserModal(p=null){
  const admin=isAdmin()||can('users.manage_all'); const roles=admin?['admin','leader','agent','custom']:['agent']; const storeOptions=accessibleStores().filter(s=>s.active); const role=p?.role||roles[0]; const scope=p?.access_scope||(role==='admin'?'global':'store');
  modal(`${p?'Editar':'Novo'} Usuário`, `<form id="userForm" class="form-grid"><div class="field"><label class="required">Nome completo</label><input class="input" name="full_name" required value="${esc(p?.full_name||'')}"></div><div class="field"><label class="required">Nome de usuário</label><input class="input" name="username" required minlength="3" maxlength="40" value="${esc(p?.username||'')}"></div><div class="field"><label class="required">Perfil</label><select class="select" name="role" id="userRole">${roles.map(r=>`<option value="${r}" ${r===role?'selected':''}>${esc(roleLabel(r))}</option>`).join('')}</select></div><div class="field"><label>Escopo</label><select class="select" name="access_scope" id="userScope"><option value="store" ${scope==='store'?'selected':''}>Uma loja</option><option value="global" ${scope==='global'?'selected':''} ${!admin?'disabled':''}>Rede Geral</option></select></div><div class="field full" id="userStoreField"><label class="required">Loja</label><select class="select" name="store_id" id="userStore"><option value="">Selecione</option>${storeOptions.map(s=>`<option value="${s.id}" ${s.id===p?.store_id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><div class="field full"><label>${p?'Nova senha (opcional)':'Senha inicial'}</label><input class="input" type="password" name="password" ${p?'':'required'} autocomplete="new-password" placeholder="Mínimo 10 caracteres, maiúscula, minúscula, número e símbolo"><div class="help">Não use o nome de usuário dentro da senha.</div></div><div class="field full" id="permissionsArea"></div></form>`,`<button class="btn ghost" data-close>Cancelar</button><button class="btn primary" id="saveUser">Salvar usuário</button>`,'large');
  const updateRoleUI=()=>{const r=$('#userRole').value;if(r==='admin'){$('#userScope').value='global';$('#userScope').disabled=true}else $('#userScope').disabled=!admin;const global=$('#userScope').value==='global';$('#userStoreField').style.display=global?'none':'block';$('#userStore').required=!global;$('#permissionsArea').innerHTML=r==='custom'?`<label>Permissões personalizadas</label><div class="permission-grid">${PERMISSIONS.map(([v,l])=>`<label class="permission-item"><input type="checkbox" name="permissions" value="${v}" ${(p?.permissions||[]).includes(v)?'checked':''}><span><strong>${esc(l)}</strong><small>${esc(v)}</small></span></label>`).join('')}</div>`:'';icons()};$('#userRole').onchange=updateRoleUI;$('#userScope').onchange=updateRoleUI;updateRoleUI();
  $('#saveUser').onclick=async()=>{const f=$('#userForm');if(!f.reportValidity())return;const fd=new FormData(f),body={action:p?'update':'create',user_id:p?.id,full_name:fd.get('full_name').trim(),username:fd.get('username').trim().toLowerCase(),role:fd.get('role'),access_scope:$('#userScope').value,store_id:$('#userScope').value==='global'?null:fd.get('store_id'),permissions:fd.getAll('permissions'),active:p?.active!==false};const pwd=fd.get('password');if(pwd)body.password=pwd;setLoading(true,'Salvando usuário...');try{const res=await callManageUser(body);if(res.error)throw new Error(res.error);closeModal();await loadData({quiet:true});toast('Usuário salvo com sucesso.')}catch(e){toast('Não foi possível salvar o usuário.','error',e.message)}finally{setLoading(false)}};icons()
}
async function callManageUser(body){const {data:{session}}=await supabase.auth.getSession();const r=await fetch(`${SUPABASE_URL}/functions/v1/manage-user`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':`Bearer ${session?.access_token||''}`},body:JSON.stringify(body)});let json={};try{json=await r.json()}catch{};if(!r.ok&&!json.error)json.error=`Erro ${r.status}`;return json}
async function toggleUser(p){setLoading(true,p.active?'Desativando usuário...':'Ativando usuário...');try{const res=await callManageUser({action:'update',user_id:p.id,username:p.username,full_name:p.full_name,role:p.role,access_scope:p.access_scope,store_id:p.store_id,permissions:p.permissions||[],active:!p.active});if(res.error)throw new Error(res.error);await loadData({quiet:true});toast(p.active?'Usuário desativado.':'Usuário ativado.')}catch(e){toast('Não foi possível alterar o usuário.','error',e.message)}finally{setLoading(false)}}
function deleteUser(p){modal('Excluir usuário',`<div class="danger-zone"><strong>Exclusão de usuário</strong><p>Se este usuário possuir histórico vinculado, o banco poderá impedir a exclusão. Nesse caso, mantenha-o desativado para preservar a auditoria.</p></div><p>Usuário: <strong>${esc(p.full_name)}</strong> (@${esc(p.username)})</p>`,`<button class="btn ghost" data-close>Cancelar</button><button class="btn danger" id="confirmDeleteUser">Excluir usuário</button>`,'small');$('#confirmDeleteUser').onclick=async()=>{setLoading(true,'Excluindo usuário...');try{const res=await callManageUser({action:'delete',user_id:p.id});if(res.error)throw new Error(res.error);closeModal();await loadData({quiet:true});toast('Usuário excluído.')}catch(e){toast('Não foi possível excluir. Desative o usuário para preservar o histórico.','error',e.message)}finally{setLoading(false)}}}

function renderAccount(){
  const p=state.profile;setPage('Minha Conta','Dados pessoais e segurança');
  $('#content').innerHTML=`${pageHeader('Minha Conta','Gerencie seu acesso ao sistema.','')}<div class="grid two-col"><section class="card"><div class="card-head"><div><h3>Meu perfil</h3><p>Informações da conta</p></div>${isPrimary()?'<span class="primary-account"><i data-lucide="shield"></i>Administrador Principal</span>':''}</div><div style="display:flex;gap:18px;align-items:center;margin-bottom:18px"><div class="mascot-ring" style="margin:0;width:90px;height:90px"><img src="./assets/nilo-mascote.webp" alt=""></div><div><h3 style="margin:0">${esc(p.full_name)}</h3><p style="color:var(--muted);margin:4px 0">@${esc(p.username)}</p><span class="role-badge">${esc(roleLabel(p.role))}</span></div></div><div class="metric-row"><span>Escopo</span><strong>${p.access_scope==='global'?'Rede Geral':esc(activeStoreName(p.store_id))}</strong></div><div class="metric-row"><span>Status</span><strong>Ativo</strong></div><div class="metric-row"><span>Identidade do sistema</span><strong>Triela Soluções</strong></div><div style="margin-top:14px;background:#fff;border:1px solid var(--line);border-radius:10px;padding:10px"><img src="./assets/triela-logo.jpg" alt="Triela Soluções" style="max-width:250px"></div></section><section class="card"><div class="card-head"><div><h3>Alterar acesso</h3><p>Todos podem trocar a senha. Administradores também podem trocar o próprio usuário.</p></div></div><form id="accountForm" class="form-grid"><div class="field full"><label>Nome de usuário</label><input class="input" name="username" value="${esc(p.username)}" ${p.role==='admin'?'':'disabled'}><div class="help">${p.role==='admin'?'Você pode alterar seu nome de usuário.':'Seu perfil não permite alterar o nome de usuário.'}</div></div><div class="field full"><label class="required">Senha atual</label><input class="input" type="password" name="current_password" required autocomplete="current-password"></div><div class="field"><label>Nova senha</label><input class="input" type="password" name="password" autocomplete="new-password"></div><div class="field"><label>Confirmar nova senha</label><input class="input" type="password" name="password2" autocomplete="new-password"></div><div class="field full"><button class="btn primary" type="submit">Salvar alterações de acesso</button></div></form></section></div>`;
  $('#accountForm').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget),pwd=fd.get('password')||'',pwd2=fd.get('password2')||'';if(pwd!==pwd2){toast('As novas senhas não conferem.','warning');return}const username=p.role==='admin'?String(fd.get('username')).trim().toLowerCase():p.username;if(username===p.username&&!pwd){toast('Informe uma nova senha ou altere o nome de usuário.','warning');return}setLoading(true,'Atualizando acesso...');try{const res=await callManageUser({action:'self_update',username,current_password:fd.get('current_password'),password:pwd});if(res.error)throw new Error(res.error);toast('Acesso atualizado. Entre novamente com seus novos dados.');setTimeout(()=>supabase.auth.signOut(),900)}catch(e){toast('Não foi possível atualizar sua conta.','error',e.message)}finally{setLoading(false)}};icons()
}

function renderAudit(){
  setPage('Auditoria','Histórico de ações importantes no sistema'); const list=state.audit;
  $('#content').innerHTML=`${pageHeader('Auditoria','Logins e mudanças de cadastros, coletas, equipamentos e usuários.','')}<div class="filters"><input id="auditSearch" class="input grow" placeholder="Buscar ação, usuário ou entidade..."></div><section id="auditList" class="card">${auditTable(list)}</section>`;$('#auditSearch').oninput=e=>{const q=e.target.value.toLowerCase();$('#auditList').innerHTML=auditTable(list.filter(a=>[a.action,a.entity_type,a.entity_id,profileById(a.user_id)?.full_name,JSON.stringify(a.details||{})].join(' ').toLowerCase().includes(q)));icons()};icons()
}
function auditTable(list){if(!list.length)return empty('Nenhum registro de auditoria disponível.','shield-check');return `<div class="table-wrap"><table class="table"><thead><tr><th>Data/Hora</th><th>Usuário</th><th>Ação</th><th>Entidade</th><th>Detalhes</th></tr></thead><tbody>${list.slice(0,1000).map(a=>`<tr><td>${fmtDateTime(a.created_at)}</td><td>${esc(profileById(a.user_id)?.full_name||a.user_id||'Sistema')}</td><td><strong>${esc(a.action)}</strong></td><td>${esc(a.entity_type||'—')}<br><small>${esc(a.entity_id||'')}</small></td><td><div class="audit-details" title="${esc(JSON.stringify(a.details||{}))}">${esc(JSON.stringify(a.details||{}))}</div></td></tr>`).join('')}</tbody></table></div>`}

function modal(title,body,footer='',size=''){const host=$('#modalHost');host.classList.remove('hidden');document.body.classList.add('modal-open');host.innerHTML=`<div class="modal ${size}"><div class="modal-header"><h3>${esc(title)}</h3><button class="modal-close" data-close><i data-lucide="x"></i></button></div><div class="modal-body">${body}</div><div class="modal-footer">${footer}</div></div>`;$$('[data-close]',host).forEach(b=>b.onclick=closeModal);host.onclick=e=>{if(e.target===host)closeModal()};icons()}
function closeModal(){$('#modalHost').classList.add('hidden');$('#modalHost').innerHTML='';document.body.classList.remove('modal-open')}
function openSidebar(){$('#sidebar').classList.add('open');$('#sidebarBackdrop').classList.remove('hidden')}
function closeSidebar(){$('#sidebar').classList.remove('open');$('#sidebarBackdrop').classList.add('hidden')}

async function handleLogin(e){e.preventDefault();const u=$('#loginUsername').value.trim().toLowerCase(),password=$('#loginPassword').value;if(!u||!password)return;setLoading(true,'Entrando...');try{const {data,error}=await supabase.auth.signInWithPassword({email:`${u}@${EMAIL_DOMAIN}`,password});if(error)throw error;state.session=data.session;state.user=data.user;await loadData({quiet:true});showApp()}catch(err){toast('Não foi possível entrar.','error',/Invalid login credentials/i.test(err.message)?'Usuário ou senha incorretos.':err.message)}finally{setLoading(false)}}
function showLogin(){$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');state.session=null;state.user=null;state.profile=null;destroyCharts();if(state.realtime){supabase.removeChannel(state.realtime);state.realtime=null}}
function showApp(){$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');renderShell();renderRoute()}

async function init(){
  $('#loginForm').addEventListener('submit',handleLogin);$('#togglePassword').onclick=()=>{const i=$('#loginPassword');i.type=i.type==='password'?'text':'password';$('#togglePassword').innerHTML=`<i data-lucide="${i.type==='password'?'eye':'eye-off'}"></i>`;icons()};$('#openSidebar').onclick=openSidebar;$('#closeSidebar').onclick=closeSidebar;$('#sidebarBackdrop').onclick=closeSidebar;$('#logoutBtn').onclick=()=>supabase.auth.signOut();$('#refreshBtn').onclick=()=>loadData();$('#quickCollectionBtn').onclick=()=>openCollectionModal();
  supabase.auth.onAuthStateChange(async(event,session)=>{state.session=session;state.user=session?.user||null;if(event==='SIGNED_OUT'||!session){showLogin();return}if(event==='SIGNED_IN'&&session){try{await loadData();showApp()}catch(e){toast('Falha ao carregar seu perfil.','error',e.message);showLogin()}}});
  setLoading(true,'Preparando sistema...');try{const {data:{session}}=await supabase.auth.getSession();if(session){state.session=session;state.user=session.user;await loadData({quiet:true});showApp()}else showLogin()}catch(e){console.error(e);showLogin()}finally{setLoading(false);icons()}
}
init();
